include("samples:guava")
include("samples:jackson")
include("samples:jmh")
include("samples:lombok")
include("samples:mockito")
include("samples:mybatis")
include("samples:reflection")
include("samples:memory-measurements")
include("samples:benchmarks")
include("samples:spring-freemarker")
include("samples:spring-i18n")

includeBuild("collection/collections")
includeBuild("testing/junit5")
