name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run docs:build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: .vitepress/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
